
const data= {
    products:[
        {
            _id:'1',
            name:'P20',
            category:'Huawei',
            image: '/images/P20hu.webp',
            countInStock: 10,
            price:20000,
            brand:'P',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'P20',
            category:'Huawei',
            image:'/images/P20hu.webp',
            countInStock: 10,
            price:20000,
            brand:'P',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'P20',
            category:'Huawei',
            image:'/images/P20hu.webp',
            countInStock: 10,
            price:20000,
            brand:'P',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'P20',
            category:'Huawei',
            image:'/images/P20hu.webp',
            countInStock: 10,
            price:20000,
            brand:'P',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'P20',
            category:'Huawei',
            image:'/images/P20hu.webp',
            countInStock: 10,
            price:20000,
            brand:'P',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'P20',
            category:'Huawei',
            image:'/images/P20hu.webp',
            countInStock: 10,
            price:20000,
            brand:'P',
            rating: 4.5,
            numReviews:10,
            description:'high quality product',
        }
    ]
}


export default data;